Update and rename codemagic (2).yaml to codemagic.yaml

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -44,12 +44,14 @@ workflows:
         recipients:
           - mark@nevercode.io
       scripts:
-        - "#!/usr/bin/env bash\n \nset -e   # exit on first failed command\nset -x\
-          \   # print all executed commands to the log\n \nif [ \"$FCI_BUILD_STEP_STATUS\"\
-          \ == \"success\" ]\nthen\n\n  # iOS Firebase App Distribution CLI\n  firebase\
-          \ appdistribution:distribute $FCI_BUILD_OUTPUT_DIR/flutterapptest.ipa --app\
-          \ 1:65771059764:ios:b6f523b0d5c2829dd4e861 --groups \"test\" --token \"\
-          $FIREBASE_TOKEN\"\n\nfi\n"
+        - #!/usr/bin/env bash
+          set -e   # exit on first failed command
+          set -x   # print all executed commands to the log
+          if [ "$FCI_BUILD_STEP_STATUS" == "success" ]
+          then
+            # iOS Firebase App Distribution CLI
+            firebase appdistribution:distribute $FCI_BUILD_OUTPUT_DIR/flutterapptest.ipa --app 1:65771059764:ios:b6f523b0d5c2829dd4e861 --groups "test" --token "$FIREBASE_TOKEN"
+          fi
   android:
     name: Android
     max_build_duration: 60
@@ -104,103 +106,6 @@ workflows:
           \  firebase appdistribution:distribute $FCI_BUILD_OUTPUT_DIR/app-release.apk\
           \ --app 1:65771059764:android:bd12e6184e171352d4e861 --groups \"test\" --token\
           \ \"$FIREBASE_TOKEN\"\n\nfi\n"
-  ios-randapisend:
-    name: iOS RandAPIsend
-    max_build_duration: 60
-    environment:
-      vars:
-        FIREBASE_TOKEN: 1//0cQj_4GQcN1O9CgYIARAAGAwSNwF-L9IrWhBxfO-TrSWG3dwdONpBy2Lx01PlrmXN2KPDBI06fbf0Hm7RKsN9yuImUlcKPwkQiOA
-        IOS_FIREBASE_SECRET: 'PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCFET0NUWVBFIHBsaXN0IFBVQkxJQyAiLS8vQXBwbGUvL0RURCBQTElTVCAxLjAvL0VOIiAiaHR0cDovL3d3dy5hcHBsZS5jb20vRFREcy9Qcm9wZXJ0eUxpc3QtMS4wLmR0ZCI+CjxwbGlzdCB2ZXJzaW9uPSIxLjAiPgo8ZGljdD4KCTxrZXk+Q0xJRU5UX0lEPC9rZXk+Cgk8c3RyaW5nPjY1NzcxMDU5NzY0LWFobXBsbzkyazg1dTdhbnYycjlmbm9mcWFwYThibWFyLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tPC9zdHJpbmc+Cgk8a2V5PlJFVkVSU0VEX0NMSUVOVF9JRDwva2V5PgoJPHN0cmluZz5jb20uZ29vZ2xldXNlcmNvbnRlbnQuYXBwcy42NTc3MTA1OTc2NC1haG1wbG85Mms4NXU3YW52MnI5Zm5vZnFhcGE4Ym1hcjwvc3RyaW5nPgoJPGtleT5BUElfS0VZPC9rZXk+Cgk8c3RyaW5nPkFJemFTeUJOcVJlekd5YzVRZ2UxZmtlQXI1UENNa003Qkh2Q0syYzwvc3RyaW5nPgoJPGtleT5HQ01fU0VOREVSX0lEPC9rZXk+Cgk8c3RyaW5nPjY1NzcxMDU5NzY0PC9zdHJpbmc+Cgk8a2V5PlBMSVNUX1ZFUlNJT048L2tleT4KCTxzdHJpbmc+MTwvc3RyaW5nPgoJPGtleT5CVU5ETEVfSUQ8L2tleT4KCTxzdHJpbmc+Y29tLm1hcmsuZmx1dHRlcmFwcHRlc3Q8L3N0cmluZz4KCTxrZXk+UFJPSkVDVF9JRDwva2V5PgoJPHN0cmluZz5mbHV0dGVydGVzdC1iZjAyMDwvc3RyaW5nPgoJPGtleT5TVE9SQUdFX0JVQ0tFVDwva2V5PgoJPHN0cmluZz5mbHV0dGVydGVzdC1iZjAyMC5hcHBzcG90LmNvbTwvc3RyaW5nPgoJPGtleT5JU19BRFNfRU5BQkxFRDwva2V5PgoJPGZhbHNlPjwvZmFsc2U+Cgk8a2V5PklTX0FOQUxZVElDU19FTkFCTEVEPC9rZXk+Cgk8ZmFsc2U+PC9mYWxzZT4KCTxrZXk+SVNfQVBQSU5WSVRFX0VOQUJMRUQ8L2tleT4KCTx0cnVlPjwvdHJ1ZT4KCTxrZXk+SVNfR0NNX0VOQUJMRUQ8L2tleT4KCTx0cnVlPjwvdHJ1ZT4KCTxrZXk+SVNfU0lHTklOX0VOQUJMRUQ8L2tleT4KCTx0cnVlPjwvdHJ1ZT4KCTxrZXk+R09PR0xFX0FQUF9JRDwva2V5PgoJPHN0cmluZz4xOjY1NzcxMDU5NzY0OmlvczpiNmY1MjNiMGQ1YzI4MjlkZDRlODYxPC9zdHJpbmc+CjwvZGljdD4KPC9wbGlzdD4=
-
-          '
-        APP_STORE_CONNECT_ISSUER_ID: 7d812fe2-8abd-47ca-9d27-3ed7e62d7b6d
-        APP_STORE_CONNECT_KEY_IDENTIFIER: 79WKM8X7V7
-        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(Z0FBQUFBQmdQanZlV0NVTVJWNlFjRVdjMmhtUElyY2RRLVVPTmNyRFo1cW9FUHZqTzNWWWd0ay05MXdWa1JBSW81VkxqOUk3ZkFKLWh3MXdqNmpXbjUwbDRLa1ppRVZlRUtiRldReW5rbm1wcWlDUFgtUm9uXzNXMlE0d1RVcHFRQm1RWThDSGE3OU9xbXhlcHFaT3o4YW5GZ0FrUGt4VUZWeHBsWXB0eTI0YVhQb1ZZUnY5ZmRqUmkxTXg1eW9MbHdLM2k1SkxPLWZZQXltNlZmUVgtektyUGxOdF9iQXI2X0VCekFoQXJUb3V4YkY4UTBacTRPODJ6ZWVCMlNRcmhyVUM5NEVVLWoxZV93Zk9CNk1XaE42by0tc2lsM3p5N21oZ2h0S0dZVDhOdGtueVBCdmJ3cC03YU04Q3BUTG5sV2NCOFl5TksxcXdRLXNLNEs1dklQM3dPdGFFUlhfUGVkTFpidjVPMk1NN014STBNMVVxOWJPUW5kQ0FuSVZEUjB6R1VpMF9zMFNJcmJJQm5zNXBKdF92Z2IxRXNjVXJydnpwQmxEa3NKRUpUR1VFMEk3NUxrbz0=)
-        CERTIFICATE_PRIVATE_KEY: Encrypted(Z0FBQUFBQmdQanZlN0JubzJQdDd6TXV2VGEyVGtnQ0R6UnQ1eWx6MHlBVXFvZjZ6Q2lwSmhPalVGRkJtV2dYcW1CdVRmcDV3d1FHODRfNFhqcFpRR0M1Z3ZoNFg5c2Nlc1VYUmtfYVV5SVFySTJiVVhsTHNFRjFDWUhaS0Y1X3RfbmFNQ1V4YnE1Wi1FeWlMYWRGTllBUnJ2VWJRM1hYV3BrRWo4WmlnN0JEcDBkVk9hcldVSlFrMDBCYkd6NzNjSFAtdmRiOGc0WV9WSWlTZFRnNXhiaHVUeHlFMEEwT3diVVNoYzhZdy14RGR2RnZVSXVhTU1aaU9fOHdBNlp0aWhxeFdaWktkNFZ2ODFqWXZYNWxRLV9rU2t6X1dhaXFlODNLbUowYW80MXJub3RMU1JjVDlmR3lJcUFLeC1ER3RZaHlQVWRoeTZ6b1hYMGlOVjIzMXlReG1MTWkzRFNTeFNzVWtTQ25hUGVFRGt6VHhkM0VvLTVKMzBQLXh1YVAzUlhLUjdWcmo2MlFOSTZOaEZ3V2lsMC1ycXFPekxwcjB2b1lOS2JrLXo1OU1FNU02OTdWclpRWXNYaTBQb0pBMDZ1WXNFTkVMTGU2YW5fZnNwaG5wYkZvXzk1WlIwRWltUDhRUEViSVhPMVRQbmJsSkZFWlB0MkxrRWtQVDJleXNobkZYRmlHQXVwVFhoWFJPdkxoN0E5MUVzcEpkbU1RdEpjaHl1bmhMcGZsYkx5aXlZYWlhc0hVWDFjTXp5LTFUcHptMjdOZU1VMWkxNFhHUTRrQThNLW1iR3JwR2U1TUFvS3JqTzNfN19YWi1LSkNCQW02SmVVVWZfUnpkNlctQjJnT090eWJFdmtqSk02VXk4dF84RXoxTVNPdmdnazNReGVyRkY1ZTJDQU1FeWl3V0twM1ZxOThOQzlEZC1DWG1rblo5cnQzcTUzT0tTUEhOQ3RqemRlbWkxc2paRkFnTG52WHNoSkhuZ0lXYlYwYkZkWG0xMHRzWjRYV2xGTUxZNm0zcVdmQVJENEl2OURrZzhIQTFFcHA0clRHUzRHY1RsTHR0anppMjlWXzdJQmRhd1B0RjJGcHptaE1sZ1pGRXpCMWY1clQ2TjZHUThhd1FmUHhULUEyWGVNTGJwM2thSlVkX0g2RWxLd2tUaUZ4NVI3NTlUWUtYckI5VlNvNXpuY2tUS244OU9KakE3STloRW9yM2x3UXdoV0pQN1R4ZFdfb01zS1gydGFocEtGaGRITFhUczEtejhkU280RzVMenp0N0YwdGlodlJFSXZrcWZXc0dkM3o5T09kb0h0RWlYdmU2ZjJrc1lETjUxblpOU1h6TjJZQ2RrTkRteUYwV2xRWkhxUG93ZzJwaWo5bUkzandnZWMwbVlZcHhlNVFBNzNuZzBlMjQ0TWdTWno1WjhKTzI1OGRZZ2lfeTRieWltZ2FOaUpXZm1TMjFZYzdVTGZkNjAwU2tlNGJ3S2g0ZTY3ME1jX3ZXc1dBRGNzNFhCd2l2alVvRkIwclpQRmNMZ1didTB2b3dhbE5oLTY3dkdWdGVkTUhmbDdieHRiVmV1YUdtZXNUWDBuUWRxNTFFQ3dpWnhTaVZZUjUweGhEX2VVYXVCb2w4aVFYQUFVSUt4WmpNZjVKRHJCcExLalZCZFIwUHQzNldDVE9lZVlfbm1pRW9CWEVReVlaWXNhbkMyWlFuNWtBU3ZxWWxzRXVJdWVQMGY5bHpweUVCNjUtSUU3ZlRBZXI3UVlhdG9KRTlBSGRtZHRmRmEwREkzR3JRanBBNld3cFFsdjFjSGViR3NkMTRqZURnd0x4akhPdTZ4N25tRGNKV0FhSGl6THFlN0xMLTRTSVdHUXJuMGtXRHo4N1RtUDBIUEU5V2k4ZnlLMGZYckExV2ZWdjNEcjlMcGFfaDFNaDJnOURQamxaUklvTG9yUWpKTEdiWmc3STBycmdOUmhuMXd5N1RHRklObTNMY29IeTBOY2JJQ2xaUFJ3Tm5iV1k1YkFKVHEwaWVxQTdpQWRRQ2FxbV9oUDl2dm9MdVVKS0FhVGNXbUJxZ2stQnRIVm51UjVybnVHeVZIcmQwZW9BZTBBazBraHQ0VFdLeEtYajhHSkJfVXVkZkJ3WVVwVmpmVDJia1ZZNEVvUkpnZ1Jxc1U0alRpQ1l1N3hFclhLOEdCNnJ0U281T1FJaTBuTUJ5dWhqRGFHVWxrYS1Mci1tYTNHd1FCSU1EOVdWTjhTZjE5Mkx4T0dENjBHY21vMnd3OXR2ZWNhV3Q5UVBrZVpTRDdhcHNTRFF4ZFFlMlgyZG9jekh4N1NSTWVXaU55VmRQQ1RkRTZPRmFINFNQWWd6UVdLWlRIUV81Zmg2ajVqSURfVXRJZFp3eG0zVDYtU0E1TG1va2pOd2czZjZyRzRmdDV2Qko5Nkg2VXdMZWJOX3lJVHpLQmFxVDh5X09SYllsV19YTENzT0tDX3NPUkZlY3ZSaGtZVVhnY0tlQm81WDFyRUl1X2IxSnBOQmp1V2ROdHk4eDVfYlJYTjJkVGxpeFphTzFudW1qNXd2ZnhYSW81N1Zyd3c0UmRJVnA4V3B2ZFhOQkJJVC1qajQtY0tzby1xUHhicU5NRHNNWU5GcnB0NndkWGVYcWczcEtvbktVdDVlNzRuLTB1Q2NzZ3Q0S3ljY09PQ1NYZXFUOEMzMEFqemE3elNwdFpYejlkX0RkQl9HeG5IcWFyODI1bzlnWVlwRHBJc3ZJV2daM1JzeXlmWG5aVEJicFVpLVJQYlp6bWd2VGYwSGVPTzYwZDNnWlI4TVdja1F5UnAtamtxY0NpMld1cFB6Z18zMXlsSHNxbDdqNEdDZXh3MUNYV1ZhWDUxVVpQZEZYNUpQRDUtbWU4MEVadmYxVHhJbFRGS1BpbXNyY3lNQ1Yycy1tYmVkdDFzTFlnam9oUUtNLWFXaHRLSmk0ejE5OEtVUVlTQTBrZ19DalZzNUJmQWlqeFprNVVaczlaaTlOOThpTW5CaVp3T3lxNGloVDh5Nlg1OVpYNzlqeWJ0TTZTalBnSE9fUDJaV05TT3Bsb3ZwWjZDZXRKaGRL)
-      flutter: stable
-      xcode: latest
-      cocoapods: default
-    scripts:
-      - cd . && flutter packages pub get
-      - |
-        #!/usr/bin/env sh
-        set -e # exit on first failed command
-
-        echo $IOS_FIREBASE_SECRET | base64 --decode > $FCI_BUILD_DIR/ios/Runner/GoogleService-Info.plist
-      - find . -name "Podfile" -execdir pod install \;
-      - keychain initialize
-      - app-store-connect fetch-signing-files "com.mark.flutterapptest" --type IOS_APP_DEVELOPMENT
-        --create
-      - keychain add-certificates
-      - cd . && flutter build ios --release --build-name=1.0.0 --build-number=$BUILD_NUMBER
-        --no-codesign
-      - xcode-project use-profiles
-      - cd . && xcode-project build-ipa --workspace "ios/Runner.xcworkspace" --scheme
-        "Runner"
-    artifacts:
-      - build/ios/ipa/*.ipa
-      - /tmp/xcodebuild_logs/*.log
-      - flutter_drive.log
-    publishing:
-      email:
-        recipients:
-          - mark@nevercode.io
-      scripts:
-        - "#!/usr/bin/env sh\n \nset -e   # exit on first failed command\nset -x \
-          \  # print all executed commands to the log\n \nif [ \"$FCI_BUILD_STEP_STATUS\"\
-          \ == \"success\" ]\nthen\n\ncurl -X POST -H 'Content-type: application/json'\
-          \ --data '{\"text\": \"Hello, world.\"}' https://hooks.slack.com/services/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\n\
-          \nfi\n"
-  ios-cmapithing:
-    name: iOS CMAPIthing
-    max_build_duration: 60
-    environment:
-      vars:
-        APP_STORE_CONNECT_ISSUER_ID: 7d812fe2-8abd-47ca-9d27-3ed7e62d7b6d
-        APP_STORE_CONNECT_KEY_IDENTIFIER: 79WKM8X7V7
-        APP_STORE_CONNECT_PRIVATE_KEY: Encrypted(Z0FBQUFBQmdQanZlWTJZOFB0QVhQb0dOanEwbU9yRGQ4cUJzZHJ5NGJIbmdXbHBSZGZqUDFMZlExMVo5ZW5aMmlMRnJ0Qm9RZUFlQmhpc0dUaDJiOXdPbEgzT3NPTVJ5b1dMRFdRNVRUaU0xZ19JQ0h3YkdHMFg5c0UzWFFhck5QWER6aHVJWDdNSkdlZXFVYm5yNkRQRHhZbnV5RXJZTnZzZGpxeWVJX1F4OVprVHRsSkkwaTNlM1RlZGFSWnFXdk5Fc2lNbXQzdkpoRDB6WmRmRlJ4LTZxSExBSmhKRDNUdFU4UjRZZlk0bkd1YmZITUd6NGY5YmdWMXBUTENpWG5XUXJxQ2NlUW5xSk5Odk4zUXZZdTdjMTJoekpfdl90Y1dBMV9sRXFydUxmMDIwd2FqMDZTY0oxY21jWnI2YnZxVTdmQ0JpQ042TkpycG1HdWhHbEdNaFZnZWVsVnFJUGhva1ZkZmhUSEFNcnFiTGdSVjROcXBxRVZ6eXFZcDFGbnNEWVBKU3dYRHY3RW9YWVotaGVKZDJLM0IxblRJWXJGTUFwcXJpbUdSX3BCVEtMcnkxVEJJRT0=)
-        CERTIFICATE_PRIVATE_KEY: Encrypted(Z0FBQUFBQmdQanZmVUMwdG15NVozRU9JcEZEVXBjSjd5d2lZVVY2Q2lMOU1naU1KNVdDV0M4UmZJRUlzQUlJZTY4UVhTQnk5aWRwZkxxclhCdjVhdVQ0RTBIM3JpQVlEb2tnX3kyU2todG1RdVdoNlZQVktIQjNka1kySm9RSmtjMm52N3hsQVNIZHUyUEhjS2xiQnRQcGdMaUQwMFlNZmFfZ0Y0SG5LQzZJSjRER0Vud2NlWGhIMkhyQkJxNlZjaDRZVzVvN24xUVFOZGpFSE13UHNpY3VwV09hYzh6RWh4TFNFRWV2S21zaTd0YnBpam1MRk1IWndMM1FYeC1zNTVQMlhzc1UyNWlDbnJGUHpWZXpsQnJYTkdfT2QtNWhqWWl3bl9KMFZHVFJJU3piOE04SzllZHhkaXZ6NVlEYkQ2MWZWaVJDdHFicjktOFRiWnhKeU9yY1ZLMGJVOEIzYVRSVXMweGU0dGtDVUFTUFZQbGNMVkRqcEFOeVBfcXRhazdxeW9iNThBVlBYWXVCNlZZNVQ5QnlMX0ozVVhYVmUwSVhmQmRDSUFCQ19jT3ZJbHVLRUQ1WTFCckpMVDd2aFdCMlVXWk91b2E1aHpCeUR2dlFnUnBBWEVlWnU4OUh4VnBrYmY2WkVDOFJYaVhJbTJKYUlJVWJKNDJmbzJsTU5pUjJzS09RdmM1SXhvalgtLTJmYWNXWEQ4RW1ONzhlY05YbEUzWmVmV3p4cXJVZWR3NjdpdTZ1dFNUcEVheXNIeXlWTTJETkMySHQ0d2RmZVFJWnE2dmJWZEtvQW9mNjVmYWY3dkVzTVVfbzV1QVEzaXo3eVBsaU1xUHR5cDFLSTBROUoyTlFONkt0SnJJOWZubERLYm1kbEo3OW0wanJhYXpkZUJnTU9wN1pMT2gwVkJVSmVvYlhGN2wwZ2FzNGhsbDBGaXlHbk9uVVZlVldMcWpONkxUQUpMWmRaZmhRVXdNUTRuUFktTHp2T0JuY3NBQzFCV3BnaWlkdWRTdXV4YXpqYTZYU1VseXZGN051Rk01RGphVTZFTmtVdUI2LXNuOTgwSUlac1o1S0tmbXB4OF9sb1RiQjdsMXNwRVNTOGhseE85dWVQdGdhVWVEX2dKOVlQYk5Lb2wxOGp5emRLZmRENkh4UjAzLVBYZjd6ZXVSV1U3VHRTOWVRY0Nwd0xkTHhQVWNCRzJ0VEVHUFdzZkcwMTNuaWRmQzBCZVdaZm1VN1pibEY0Z0luUTRFd21iM2VzUFFGXzlzd3NrS2xlTzhKZFE4Y2dWLVFYang3SC1kSlhRbGxGTFZXdGs0UWljb3gtVWxiYnNBeWdVNk1kckJ6MmNabkwwLTQ5Y3A2SldEWjdCblNldV8tb3JRTXpmU1ZyRHNzQ2JYS000VUxueDJHUlh6V2toZ2tqaENuZUpnVjUtTHB3RDdtamEtRXRMcUVSRVlZNFdRcW1RM05MVHpMVzlERDNKbXBUM0JHSlB0dXI0WTd1bkdIZlpLenJYZWJGWWJfTzJERGdIM2VNVEdrT0FVSzJ0VktBRjBuWHQ4NGlDU3JqTktwR3ZEWlM4N0gyal93ZW5kY05aWEtxVk9iNU5hR3IwU1dreGZxSmxkei1vZjJjaHVLOUFJNEdnYnNEQ0FEdVAwdTVJMDR0cHRQSjRoOUxxODhIczQydk5fMDRkejhyRXZYUHRmaVNmZmN5SkdnWldOTE5VcmtocmpHQlFybFE2OFlWcEp5cWVjQWFnRXFTcDZmbmVKTzl2cUNvWVNDNDhzQk82Y3YwNzVHY1dYWlNzeFYya3dfVWtLWXM4LTk3Q0l3SFpTTkZfdXRxWGhUV3NLdTNZbklYNDVJNDFUeTBmN2xKazdvdjBwaXQ4SGs4NzYyNm1iWU9KR2xHajk0aHNGakZwYjBMcGpYU1V3N2I2MHczTUliVTVUWXNHYXdLOEl5MHQxX1Y1WGtjZFZRQXh5d1VWLUN5Y0hLSmFDNlZYMGduaGtSU0xmYmRoblkzM1ZQSHZwR2JoWnUzTVRZRjd3enNnY1NfbTVEejBvQ2FCV2dSUlMtQ3JsTThoUHFLa1Fqc3VCcUVKekJnRktleS1IWnkweVhlOTI1Y0ptaTNreUlENXFFNmRyZHhqZERVYUxNcFV5aDZ5MV9CN2RxRllvVk1TSjd6c3FHbW9SY3dGdmJIMXdwVWJZaHliQ2V1LXJLSE9pZFFabWJtWDF0VnpvVDNzZUZGUEhHM0QyWE90QTc4TjVfZm5fLXk3b2tMOXl3Y2ZobmNWQUh6RW1JbnZ0QVRySFZ1NHNNZUdOVmhjVFZyWGM2cW4zUmtzZW1vdWwzTGVNejduaS1tVmlGeHF2YVhjX2paN1JMelhYY2d5ek00MEdWZUhNSTI4WDF6TW9LU3NrNXdRQnJrYk9FUnRsLXhRV0pnd29nR1RBSjhFekNaWFFFNkg4T1ZoMm9OcjBKdTdUQm16MXI5djFiX180S1Y0bWRkbGM0SEVYYkZzODRRRXlnNDg1b1RBaHhDamFMUThHVWxzcHV2bk5sNFBSbWVHYWM1SmwxN01IRWtDNDJWMlNTNTZFd1hDbks1b2JzeWpTUURDbkdsMGhhNUFwMm9ZamE2X1l5a3BwamRkMVFLazd3WUhZbWtPRV9pTGEzN3d3cGlVYW5KSUdQMWp5V3lmems2UDBsQjI0Q0JteFhXOWxoNTFMc05jcmFXWnZNdHFaLU1POEFSYmI3ODNRRV9MVldaTmFyZ3h2bFljMWRrY3U2N09jV0I5b0RvbjhEbDFJNlFtRXN0NEN2a3N4NWZha1cyNERyMzVxbHBvT0o2YTRlY1RHXzNiTzI3Q1pXaG82RVhtUXdJcnprd3lIRDBVVmxtN1VkSlduUGZ2eHN6QmUtYUJleVZwRjhQN3JkRHhFYUJyZXA3R050aTJmUmVsUmR3Y0s5RDE4ZllRWFZkZnUxUFhfOThKRk1zalZuQU4ybFRuNjh4VFBuSktadUx4bEh3eVpnbDNZcHNBZHFVdU9GZHFRV05LSlJSRUtCSGk4NGVLeGhCTk9KRkFsSmZTY3hTeDVra1dnbjViTENP)
-      flutter: stable
-      xcode: latest
-      cocoapods: default
-    scripts:
-      - cd . && flutter packages pub get
-      - find . -name "Podfile" -execdir pod install \;
-      - keychain initialize
-      - app-store-connect fetch-signing-files "com.mark.flutterapptest" --type IOS_APP_DEVELOPMENT
-        --create
-      - keychain add-certificates
-      - cd . && flutter build ios --release --build-name=1.0.0 --build-number=$BUILD_NUMBER
-        --no-codesign
-      - xcode-project use-profiles
-      - cd . && xcode-project build-ipa --workspace "ios/Runner.xcworkspace" --scheme
-        "Runner"
-    artifacts:
-      - build/ios/ipa/*.ipa
-      - /tmp/xcodebuild_logs/*.log
-      - flutter_drive.log
-    publishing:
-      email:
-        recipients:
-          - mark@nevercode.io
-  ios-cmapithing-testsonly:
-    name: iOS CMAPIthing testsonly
-    max_build_duration: 60
-    environment:
-      flutter: stable
-      xcode: latest
-      cocoapods: default
-    scripts:
-      - cd . && flutter packages pub get
-      - cd . && flutter test
-      - "#!/usr/bin/env sh\n \nset -e   # exit on first failed command\nset -x   #\
-        \ print all executed commands to the log\n \nif [ \"$FCI_TEST_STEP_STATUS\"\
-        \ == \"success\" ]\nthen\n\ncurl -H 'Content-type: application/json' -H \"\
-        x-auth-token: PI0Duj1pRW7ws12TLwHsvnyh1j6pFCIy-I7z7NH9GSg\" --data '{\"appId\"\
-        : \"60228dbebe2f064451fe4a6b\",\"workflowId\": \"60251424be2f0626693ccfeb\"\
-        ,\"branch\": \"main\"}' https://api.codemagic.io/builds\n\nfi\n"
-    artifacts:
-      - flutter_drive.log
   web:
     name: WEB
     max_build_duration: 60
